name: Deploy Libraries

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: java_deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Nexus host entry
        run: |
          echo "144.24.176.218 nexus.ms-repos.com" | sudo tee -a /etc/hosts

      - name: Set up JDK 17 and Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: nexus
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD

      - name: Build & Deploy all modules
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn clean deploy -pl mailer-api -am \
            -Dmaven.resolver.transport=wagon \
            -Dmaven.wagon.http.ssl.insecure=true \
            -Dmaven.wagon.http.ssl.allowall=true \
            -Dmaven.wagon.http.ssl.ignore.validity.dates=true
